### ISSUE TITLE
Problem when running BisulfiteGenotyper

### ISSUE THREAD

**Issue by LiyanJi-code** [dnaase/Bis-tools#5]
Hi,
I'm running bis-snp when using the command:
java -Xmx10G -jar BisSNP-1.0.1.jar -R hs37d5.fa -I header.sort.mdups.bam -D 00-All.vcf.gz -T BisulfiteGenotyper -vfn1 header.sort.mdups.cytosine.raw.vcf -vfn2 header.sort.mdups.snp.raw.vcf -C CG,1 -C CH,1 -out_modes EMIT_VARIANT_AND_CYTOSINES -stand_call_conf 10 -nt 12 -minConv 1 -vcfCache 1000000 -mmq 30 -mbq 5

But the following errors occur:

##### ERROR --
INFO  00:08:25,980 SAMDataSource$SAMReaders - Initializing SAMRecords in serial
##### ERROR stack trace
htsjdk.samtools.SAMFormatException: Did not inflate expected amount
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:147)
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:96)
        at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:537)
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:519)
        at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:455)
        at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:445)
        at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:194)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:236)
        at htsjdk.tribble.readers.TabixReader.readLine(TabixReader.java:200)
        at htsjdk.tribble.readers.TabixReader$IteratorImpl.next(TabixReader.java:417)
        at htsjdk.tribble.readers.TabixIteratorLineReader.readLine(TabixIteratorLineReader.java:46)
        at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:177)
        at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:215)
        at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:155)
        at org.broadinstitute.gatk.utils.refdata.utils.FeatureToGATKFeatureIterator.next(FeatureToGATKFeatureIterator.java:60)
        at org.broadinstitute.gatk.utils.refdata.utils.FeatureToGATKFeatureIterator.next(FeatureToGATKFeatureIterator.java:42)
        at org.broadinstitute.gatk.utils.iterators.PushbackIterator.next(PushbackIterator.java:65)
        at org.broadinstitute.gatk.utils.refdata.SeekableRODIterator.seekForward(SeekableRODIterator.java:356)
        at org.broadinstitute.gatk.engine.datasources.providers.ManagingReferenceOrderedView.getReferenceOrderedDataAtLocus(ManagingRe
        at org.broadinstitute.gatk.engine.traversals.TraverseLociNano$MapDataIterator.next(TraverseLociNano.java:182)
        at org.broadinstitute.gatk.engine.traversals.TraverseLociNano$MapDataIterator.next(TraverseLociNano.java:153)
        at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler.executeSingleThreaded(NanoScheduler.java:271)
        at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler.execute(NanoScheduler.java:245)
        at org.broadinstitute.gatk.engine.traversals.TraverseLociNano.traverse(TraverseLociNano.java:144)
        at org.broadinstitute.gatk.engine.traversals.TraverseLociNano.traverse(TraverseLociNano.java:92)
        at org.broadinstitute.gatk.engine.traversals.TraverseLociNano.traverse(TraverseLociNano.java:48)
        at org.broadinstitute.gatk.engine.executive.ShardTraverser.call(ShardTraverser.java:98)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
##### ERROR ------------------------------------------------------------------------------------------

Some of my bams passed through this process, while others failed. Any help would be much appreciated.

Thanks in advances.

**Comment by LiyanJi-code** [comment]
It turns out the problems with the header of input bams. The header of bams were modified with GATK AddOrReplaceReadGroups with the default parameters together with VALIDATION_STRINGENCY=LENIENT. The above problems were fixed.
